CREATE TABLE IF NOT EXISTS Role
(
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30),
    CONSTRAINT UC_ROLE UNIQUE (id, name)
    );

CREATE TABLE IF NOT EXISTS USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LOGIN VARCHAR(40) UNIQUE NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    ROLEID BIGINT NOT NULL,
    FOREIGN KEY (ROLEID) REFERENCES ROLE (ID) ON DELETE CASCADE
    );